blank_issues_enabled: false
contact_links:
  - name: 💬 Home Assistant Community Forum
    url: https://community.home-assistant.io/
    about: Ask questions or discuss with the Home Assistant community.
