name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build & Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip custom_components/enders_celsio
        run: |
          cd custom_components/enders_celsio
          zip -r ../../enders_celsio.zip .

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: enders_celsio.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
